// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using BitMEX.Model.PositionResponse;
//
//    var position = Position.FromJson(jsonString);

namespace BitMEX.Model.PositionResponse
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Position
    {
        [JsonProperty("account", NullValueHandling = NullValueHandling.Ignore)]
        public long? Account { get; set; }

        [JsonProperty("symbol", NullValueHandling = NullValueHandling.Ignore)]
        public string Symbol { get; set; }

        [JsonProperty("currency", NullValueHandling = NullValueHandling.Ignore)]
        public string Currency { get; set; }

        [JsonProperty("underlying", NullValueHandling = NullValueHandling.Ignore)]
        public string Underlying { get; set; }

        [JsonProperty("quoteCurrency", NullValueHandling = NullValueHandling.Ignore)]
        public string QuoteCurrency { get; set; }

        [JsonProperty("commission", NullValueHandling = NullValueHandling.Ignore)]
        public double? Commission { get; set; }

        [JsonProperty("initMarginReq", NullValueHandling = NullValueHandling.Ignore)]
        public double? InitMarginReq { get; set; }

        [JsonProperty("maintMarginReq", NullValueHandling = NullValueHandling.Ignore)]
        public double? MaintMarginReq { get; set; }

        [JsonProperty("riskLimit", NullValueHandling = NullValueHandling.Ignore)]
        public long? RiskLimit { get; set; }

        [JsonProperty("leverage", NullValueHandling = NullValueHandling.Ignore)]
        public long? Leverage { get; set; }

        [JsonProperty("crossMargin", NullValueHandling = NullValueHandling.Ignore)]
        public bool? CrossMargin { get; set; }

        [JsonProperty("deleveragePercentile")]
        public dynamic DeleveragePercentile { get; set; }

        [JsonProperty("rebalancedPnl", NullValueHandling = NullValueHandling.Ignore)]
        public long? RebalancedPnl { get; set; }

        [JsonProperty("prevRealisedPnl", NullValueHandling = NullValueHandling.Ignore)]
        public long? PrevRealisedPnl { get; set; }

        [JsonProperty("prevUnrealisedPnl", NullValueHandling = NullValueHandling.Ignore)]
        public long? PrevUnrealisedPnl { get; set; }

        [JsonProperty("prevClosePrice", NullValueHandling = NullValueHandling.Ignore)]
        public double? PrevClosePrice { get; set; }

        [JsonProperty("openingTimestamp", NullValueHandling = NullValueHandling.Ignore)]
        public DateTimeOffset? OpeningTimestamp { get; set; }

        [JsonProperty("openingQty", NullValueHandling = NullValueHandling.Ignore)]
        public long? OpeningQty { get; set; }

        [JsonProperty("openingCost", NullValueHandling = NullValueHandling.Ignore)]
        public long? OpeningCost { get; set; }

        [JsonProperty("openingComm", NullValueHandling = NullValueHandling.Ignore)]
        public long? OpeningComm { get; set; }

        [JsonProperty("openOrderBuyQty", NullValueHandling = NullValueHandling.Ignore)]
        public long? OpenOrderBuyQty { get; set; }

        [JsonProperty("openOrderBuyCost", NullValueHandling = NullValueHandling.Ignore)]
        public long? OpenOrderBuyCost { get; set; }

        [JsonProperty("openOrderBuyPremium", NullValueHandling = NullValueHandling.Ignore)]
        public long? OpenOrderBuyPremium { get; set; }

        [JsonProperty("openOrderSellQty", NullValueHandling = NullValueHandling.Ignore)]
        public long? OpenOrderSellQty { get; set; }

        [JsonProperty("openOrderSellCost", NullValueHandling = NullValueHandling.Ignore)]
        public long? OpenOrderSellCost { get; set; }

        [JsonProperty("openOrderSellPremium", NullValueHandling = NullValueHandling.Ignore)]
        public long? OpenOrderSellPremium { get; set; }

        [JsonProperty("execBuyQty", NullValueHandling = NullValueHandling.Ignore)]
        public long? ExecBuyQty { get; set; }

        [JsonProperty("execBuyCost", NullValueHandling = NullValueHandling.Ignore)]
        public long? ExecBuyCost { get; set; }

        [JsonProperty("execSellQty", NullValueHandling = NullValueHandling.Ignore)]
        public long? ExecSellQty { get; set; }

        [JsonProperty("execSellCost", NullValueHandling = NullValueHandling.Ignore)]
        public long? ExecSellCost { get; set; }

        [JsonProperty("execQty", NullValueHandling = NullValueHandling.Ignore)]
        public long? ExecQty { get; set; }

        [JsonProperty("execCost", NullValueHandling = NullValueHandling.Ignore)]
        public long? ExecCost { get; set; }

        [JsonProperty("execComm", NullValueHandling = NullValueHandling.Ignore)]
        public long? ExecComm { get; set; }

        [JsonProperty("currentTimestamp", NullValueHandling = NullValueHandling.Ignore)]
        public DateTimeOffset? CurrentTimestamp { get; set; }

        [JsonProperty("currentQty", NullValueHandling = NullValueHandling.Ignore)]
        public long? CurrentQty { get; set; }

        [JsonProperty("currentCost", NullValueHandling = NullValueHandling.Ignore)]
        public long? CurrentCost { get; set; }

        [JsonProperty("currentComm", NullValueHandling = NullValueHandling.Ignore)]
        public long? CurrentComm { get; set; }

        [JsonProperty("realisedCost", NullValueHandling = NullValueHandling.Ignore)]
        public long? RealisedCost { get; set; }

        [JsonProperty("unrealisedCost", NullValueHandling = NullValueHandling.Ignore)]
        public long? UnrealisedCost { get; set; }

        [JsonProperty("grossOpenCost", NullValueHandling = NullValueHandling.Ignore)]
        public long? GrossOpenCost { get; set; }

        [JsonProperty("grossOpenPremium", NullValueHandling = NullValueHandling.Ignore)]
        public long? GrossOpenPremium { get; set; }

        [JsonProperty("grossExecCost", NullValueHandling = NullValueHandling.Ignore)]
        public long? GrossExecCost { get; set; }

        [JsonProperty("isOpen", NullValueHandling = NullValueHandling.Ignore)]
        public bool? IsOpen { get; set; }

        [JsonProperty("markPrice", NullValueHandling = NullValueHandling.Ignore)]
        public double? MarkPrice { get; set; }

        [JsonProperty("markValue", NullValueHandling = NullValueHandling.Ignore)]
        public long? MarkValue { get; set; }

        [JsonProperty("riskValue", NullValueHandling = NullValueHandling.Ignore)]
        public long? RiskValue { get; set; }

        [JsonProperty("homeNotional", NullValueHandling = NullValueHandling.Ignore)]
        public long? HomeNotional { get; set; }

        [JsonProperty("foreignNotional", NullValueHandling = NullValueHandling.Ignore)]
        public long? ForeignNotional { get; set; }

        [JsonProperty("posState", NullValueHandling = NullValueHandling.Ignore)]
        public string PosState { get; set; }

        [JsonProperty("posCost", NullValueHandling = NullValueHandling.Ignore)]
        public long? PosCost { get; set; }

        [JsonProperty("posCost2", NullValueHandling = NullValueHandling.Ignore)]
        public long? PosCost2 { get; set; }

        [JsonProperty("posCross", NullValueHandling = NullValueHandling.Ignore)]
        public long? PosCross { get; set; }

        [JsonProperty("posInit", NullValueHandling = NullValueHandling.Ignore)]
        public long? PosInit { get; set; }

        [JsonProperty("posComm", NullValueHandling = NullValueHandling.Ignore)]
        public long? PosComm { get; set; }

        [JsonProperty("posLoss", NullValueHandling = NullValueHandling.Ignore)]
        public long? PosLoss { get; set; }

        [JsonProperty("posMargin", NullValueHandling = NullValueHandling.Ignore)]
        public long? PosMargin { get; set; }

        [JsonProperty("posMaint", NullValueHandling = NullValueHandling.Ignore)]
        public long? PosMaint { get; set; }

        [JsonProperty("posAllowance", NullValueHandling = NullValueHandling.Ignore)]
        public long? PosAllowance { get; set; }

        [JsonProperty("taxableMargin", NullValueHandling = NullValueHandling.Ignore)]
        public long? TaxableMargin { get; set; }

        [JsonProperty("initMargin", NullValueHandling = NullValueHandling.Ignore)]
        public long? InitMargin { get; set; }

        [JsonProperty("maintMargin", NullValueHandling = NullValueHandling.Ignore)]
        public long? MaintMargin { get; set; }

        [JsonProperty("sessionMargin", NullValueHandling = NullValueHandling.Ignore)]
        public long? SessionMargin { get; set; }

        [JsonProperty("targetExcessMargin", NullValueHandling = NullValueHandling.Ignore)]
        public long? TargetExcessMargin { get; set; }

        [JsonProperty("varMargin", NullValueHandling = NullValueHandling.Ignore)]
        public long? VarMargin { get; set; }

        [JsonProperty("realisedGrossPnl", NullValueHandling = NullValueHandling.Ignore)]
        public long? RealisedGrossPnl { get; set; }

        [JsonProperty("realisedTax", NullValueHandling = NullValueHandling.Ignore)]
        public long? RealisedTax { get; set; }

        [JsonProperty("realisedPnl", NullValueHandling = NullValueHandling.Ignore)]
        public long? RealisedPnl { get; set; }

        [JsonProperty("unrealisedGrossPnl", NullValueHandling = NullValueHandling.Ignore)]
        public long? UnrealisedGrossPnl { get; set; }

        [JsonProperty("longBankrupt", NullValueHandling = NullValueHandling.Ignore)]
        public long? LongBankrupt { get; set; }

        [JsonProperty("shortBankrupt", NullValueHandling = NullValueHandling.Ignore)]
        public long? ShortBankrupt { get; set; }

        [JsonProperty("taxBase", NullValueHandling = NullValueHandling.Ignore)]
        public long? TaxBase { get; set; }

        [JsonProperty("indicativeTaxRate", NullValueHandling = NullValueHandling.Ignore)]
        public long? IndicativeTaxRate { get; set; }

        [JsonProperty("indicativeTax", NullValueHandling = NullValueHandling.Ignore)]
        public long? IndicativeTax { get; set; }

        [JsonProperty("unrealisedTax", NullValueHandling = NullValueHandling.Ignore)]
        public long? UnrealisedTax { get; set; }

        [JsonProperty("unrealisedPnl", NullValueHandling = NullValueHandling.Ignore)]
        public long? UnrealisedPnl { get; set; }

        [JsonProperty("unrealisedPnlPcnt", NullValueHandling = NullValueHandling.Ignore)]
        public long? UnrealisedPnlPcnt { get; set; }

        [JsonProperty("unrealisedRoePcnt", NullValueHandling = NullValueHandling.Ignore)]
        public long? UnrealisedRoePcnt { get; set; }

        [JsonProperty("simpleQty")]
        public dynamic SimpleQty { get; set; }

        [JsonProperty("simpleCost")]
        public dynamic SimpleCost { get; set; }

        [JsonProperty("simpleValue")]
        public dynamic SimpleValue { get; set; }

        [JsonProperty("simplePnl")]
        public dynamic SimplePnl { get; set; }

        [JsonProperty("simplePnlPcnt")]
        public dynamic SimplePnlPcnt { get; set; }

        [JsonProperty("avgCostPrice")]
        public dynamic AvgCostPrice { get; set; }

        [JsonProperty("avgEntryPrice")]
        public dynamic AvgEntryPrice { get; set; }

        [JsonProperty("breakEvenPrice")]
        public dynamic BreakEvenPrice { get; set; }

        [JsonProperty("marginCallPrice")]
        public dynamic MarginCallPrice { get; set; }

        [JsonProperty("liquidationPrice")]
        public dynamic LiquidationPrice { get; set; }

        [JsonProperty("bankruptPrice")]
        public dynamic BankruptPrice { get; set; }

        [JsonProperty("timestamp", NullValueHandling = NullValueHandling.Ignore)]
        public DateTimeOffset? Timestamp { get; set; }

        [JsonProperty("lastPrice", NullValueHandling = NullValueHandling.Ignore)]
        public double? LastPrice { get; set; }

        [JsonProperty("lastValue", NullValueHandling = NullValueHandling.Ignore)]
        public long? LastValue { get; set; }
    }

    public partial class Position
    {
        public static List<Position> FromJson(string json)
        {
            return JsonConvert.DeserializeObject<List<Position>>(json, BitMEX.Model.PositionResponse.Converter.Settings);
        }
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
