// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using BitMEX.Model;
//
//    var walletResponse = WalletResponse.FromJson(jsonString);

namespace BitMEX.Model
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class WalletResponse
    {
        [JsonProperty("account")]
        public long Account { get; set; }

        [JsonProperty("currency")]
        public string Currency { get; set; }

        [JsonProperty("prevDeposited")]
        public long PrevDeposited { get; set; }

        [JsonProperty("prevWithdrawn")]
        public long PrevWithdrawn { get; set; }

        [JsonProperty("prevTransferIn")]
        public long PrevTransferIn { get; set; }

        [JsonProperty("prevTransferOut")]
        public long PrevTransferOut { get; set; }

        [JsonProperty("prevAmount")]
        public long PrevAmount { get; set; }

        [JsonProperty("prevTimestamp")]
        public DateTimeOffset PrevTimestamp { get; set; }

        [JsonProperty("deltaDeposited")]
        public long DeltaDeposited { get; set; }

        [JsonProperty("deltaWithdrawn")]
        public long DeltaWithdrawn { get; set; }

        [JsonProperty("deltaTransferIn")]
        public long DeltaTransferIn { get; set; }

        [JsonProperty("deltaTransferOut")]
        public long DeltaTransferOut { get; set; }

        [JsonProperty("deltaAmount")]
        public long DeltaAmount { get; set; }

        [JsonProperty("deposited")]
        public long Deposited { get; set; }

        [JsonProperty("withdrawn")]
        public long Withdrawn { get; set; }

        [JsonProperty("transferIn")]
        public long TransferIn { get; set; }

        [JsonProperty("transferOut")]
        public long TransferOut { get; set; }

        [JsonProperty("amount")]
        public long Amount { get; set; }

        [JsonProperty("pendingCredit")]
        public long PendingCredit { get; set; }

        [JsonProperty("pendingDebit")]
        public long PendingDebit { get; set; }

        [JsonProperty("confirmedDebit")]
        public long ConfirmedDebit { get; set; }

        [JsonProperty("timestamp")]
        public DateTimeOffset Timestamp { get; set; }

        [JsonProperty("addr")]
        public string Addr { get; set; }

        [JsonProperty("script")]
        public string Script { get; set; }

        [JsonProperty("withdrawalLock")]
        public List<object> WithdrawalLock { get; set; }
    }

    public partial class WalletResponse
    {
        public static WalletResponse FromJson(string json)
        {
            return JsonConvert.DeserializeObject<WalletResponse>(json, WalletConverter.Settings);
        }
    }
    
    internal static class WalletConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
