/* 
 * BitMEX Testnet API
 *
 * ## REST API for the BitMEX Trading Platform  [View Changelog](/app/apiChangelog)  - -- -  #### Getting Started  Base URI: [https://testnet.bitmex.com/api/v1](/api/v1)  ##### Fetching Data  All REST endpoints are documented below. You can try out any query right from this interface.  Most table queries accept `count`, `start`, and `reverse` params. Set `reverse=true` to get rows newest-first.  Additional documentation regarding filters, timestamps, and authentication is available in [the main API documentation](/app/restAPI).  *All* table data is available via the [Websocket](/app/wsAPI). We highly recommend using the socket if you want to have the quickest possible data without being subject to ratelimits.  ##### Return Types  By default, all data is returned as JSON. Send `?_format=csv` to get CSV data or `?_format=xml` to get XML data.  ##### Trade Data Queries  *This is only a small subset of what is available, to get you started.*  Fill in the parameters and click the `Try it out!` button to try any of these queries.  * [Pricing Data](#!/Quote/Quote_get)  * [Trade Data](#!/Trade/Trade_get)  * [OrderBook Data](#!/OrderBook/OrderBook_getL2)  * [Settlement Data](#!/Settlement/Settlement_get)  * [Exchange Statistics](#!/Stats/Stats_history)  Every function of the BitMEX.com platform is exposed here and documented. Many more functions are available.  ##### Swagger Specification  [⇩ Download Swagger JSON](swagger.json)  - -- -  ## All API Endpoints  Click to expand a section. 
 *
 * OpenAPI spec version: 1.2.0
 * Contact: support@bitmex.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// UserCommissionsBySymbol
    /// </summary>
    [DataContract]
    public partial class UserCommissionsBySymbol : Dictionary<String, UserCommission>,  IEquatable<UserCommissionsBySymbol>//, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserCommissionsBySymbol" /> class.
        /// </summary>
        /// <param name="symbol_">symbol_.</param>
        public UserCommissionsBySymbol(UserCommission symbol_ = default(UserCommission)) : base()
        {
            this.Symbol_ = symbol_;
        }
        
        /// <summary>
        /// Gets or Sets Symbol_
        /// </summary>
        [DataMember(Name="__symbol__", EmitDefaultValue=false)]
        public UserCommission Symbol_ { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UserCommissionsBySymbol {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  Symbol_: ").Append(Symbol_).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UserCommissionsBySymbol);
        }

        /// <summary>
        /// Returns true if UserCommissionsBySymbol instances are equal
        /// </summary>
        /// <param name="input">Instance of UserCommissionsBySymbol to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UserCommissionsBySymbol input)
        {
            if (input == null)
                return false;

            return base.Equals(input) && 
                (
                    this.Symbol_ == input.Symbol_ ||
                    (this.Symbol_ != null &&
                    this.Symbol_.Equals(input.Symbol_))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                if (this.Symbol_ != null)
                    hashCode = hashCode * 59 + this.Symbol_.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        //IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        //{
        //    foreach(var x in base.Validate(validationContext)) yield return x;
        //    yield break;
        //}
    }

}
